# Generated by Django 3.2.13 on 2022-11-17 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_follwings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='follwings',
            new_name='followings',
        ),
    ]
